project: unloan/xsd2ts

# Additional repositories related to your project
repos:
- unloan/xsd2ts

# Files and folders to send to TAC for review
include:
- README.md

# Can be also be a glob pattern, example:
# - docs/**
